### ISSUE TITLE
PRs from a different user?

### ISSUE THREAD

**Issue by tdhock** [analyticalmonk/Rperform#2]
how to get a list of commits when the PR comes from a different user?

for example https://github.com/tdhock/animint/pull/78

**Comment by tdhock** [comment]
travis environment variables http://docs.travis-ci.com/user/environment-variables/

**Comment by tdhock** [comment]
TRAVIS_BRANCH: For builds not triggered by a pull request this is the name of the branch currently being built; whereas for builds triggered by a pull request this is the name of the branch targeted by the pull request (in many cases this will be master).

**Comment by tdhock** [comment]
TRAVIS_PULL_REQUEST: The pull request number if the current job is a pull request, “false” if it’s not a pull request.

**Comment by tdhock** [comment]
TRAVIS_REPO_SLUG: The slug (in form: owner_name/repo_name) of the repository currently being built. (for example, “travis-ci/travis-build”).

**Comment by tdhock** [comment]
say that you submit a PR from da-ta-vinci21/stringr@some_branch to hadley/stringr@master

TRAVIS_PULL_REQUEST=128 (some number)
TRAVIS_BRANCH=some_branch
TRAVIS_REPO_SLUG=da-ta-vinci21/stringr

question: how to determine hadley/stringr@master (target of PR)?

**Comment by tdhock** [comment]
if you can't figure it out post an issue to Travis https://github.com/travis-ci/travis-ci/issues/new

**Comment by analyticalmonk** [comment]
I was going through the travis docs and came across this: [Security Restrictions when testing Pull Requests](http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests). It mentions how the secure or encrypted environment variables won't be available when building a PR from a fork of the repository. That means a PR build won't have access to the encrypted github token which is used to push to the github page.
Even if we were to figure out a way to determine the target of PR, it won't do us any good since we won't be able to update the gh-page!

**Comment by tdhock** [comment]
ok that makes sense.

in that case I guess it is OK to only support PRs from the same repos.
