### ISSUE TITLE
An error message popped up when using

### ISSUE THREAD

**Issue by LooDaHu** [analyticalmonk/Rperform#44]
Hi, @analyticalmonk . I got an error message when I try to reproduce examples at the README page. I forked your _stringr_ repo and committed twice with some small changes in test-join.r. Then I tried plot_metrics and I got an error message, Here is the console log:
```
> getwd()
[1] "C:/Users/65112/Documents/stringr"
> plot_metrics(test_path = "tests/testthat/test-join.r", metric = "time", num_commits = 2, save_data = FALSE, save_plots = FALSE)
Error in base::substr(commit_val@summary, start = 1, stop = 15) : 
  trying to get slot "summary" from an object (class "git_commit") that is not an S4 object 
```
There is no error message when num_commits = 0 and no plot comes out.
Could you help me with this problem? Thank you in advance.

**Comment by analyticalmonk** [comment]
Hi @LooDaHu,
It seems that this could be because of a change in one of the dependency packages. I'll have a look at get back to you in a day or two.

**Comment by analyticalmonk** [comment]
Hi @LooDaHu,
It took me some time before I got the chance to look at this. This error occurred due to the breaking changes that had happened to git2r sometime back due to them switching to S3 objects from S4. The latest git2r version that Rperform will work with is `0.21.0`. 

As a temporary fix, I've modified the DESCRIPTION file. I've also opened an issue here: https://github.com/analyticalmonk/Rperform/issues/45

Please let me know if this helps.

**Comment by LooDaHu** [comment]
Hi @analyticalmonk,
Thanks for the info, this is helpful.
